// Mock for realScannerData.js
// Avoids actual fetch calls in tests
// Uses jest.fn() to enable .mockResolvedValueOnce() etc.

const mockScannerData = {
  total_repositories: 500,
  total_packages: 500,
  average_quality_score: 78.5,
  total_scans: 500,
  security_stats: {
    total_findings: 42,
    critical: 5,
    high: 12,
    medium: 15,
    low: 10,
  },
  security_pattern_distribution: {
    'Dependency vulnerabilities': 8,
    'SQL injection': 2,
    'Code injection': 3,
    XSS: 5,
    Crypto: 4,
    Secrets: 6,
    Config: 4,
  },
  tier_distribution: { A: 200, B: 150, C: 100, D: 40, F: 10 },
  language_distribution: {
    JavaScript: 150,
    Python: 120,
    TypeScript: 80,
    Java: 50,
    Go: 40,
    Rust: 30,
    'C++': 20,
    Ruby: 10,
  },
  top_languages: [
    { language: 'JavaScript', count: 150, avgScore: 80.2 },
    { language: 'Python', count: 120, avgScore: 78.5 },
    { language: 'TypeScript', count: 80, avgScore: 82.1 },
    { language: 'Java', count: 50, avgScore: 75.0 },
    { language: 'Go', count: 40, avgScore: 79.3 },
    { language: 'Rust', count: 30, avgScore: 85.0 },
    { language: 'C++', count: 20, avgScore: 72.0 },
    { language: 'Ruby', count: 10, avgScore: 70.0 },
  ],
  recent_scans: [
    {
      id: 'repo-1',
      name: 'facebook/react',
      repo_name: 'facebook/react',
      language: 'JavaScript',
      stars: 225000,
      quality_score: 92,
      tier: 'A',
      scan_date: '2026-06-25T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 4,
      total_files: 15000,
      forks: 45000,
      description: 'React library',
      topics: ['react', 'ui', 'javascript'],
    },
    {
      id: 'repo-2',
      name: 'microsoft/vscode',
      repo_name: 'microsoft/vscode',
      language: 'TypeScript',
      stars: 155000,
      quality_score: 88,
      tier: 'A',
      scan_date: '2026-06-24T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 80,
      total_files: 90000,
      forks: 28000,
      description: 'Visual Studio Code',
      topics: ['editor', 'typescript', 'electron'],
    },
    {
      id: 'repo-3',
      name: 'django/django',
      repo_name: 'django/django',
      language: 'Python',
      stars: 78000,
      quality_score: 85,
      tier: 'A',
      scan_date: '2026-06-23T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 45,
      total_files: 25000,
      forks: 35000,
      description: 'Django framework',
      topics: ['django', 'python', 'web'],
    },
    {
      id: 'repo-4',
      name: 'golang/go',
      repo_name: 'golang/go',
      language: 'Go',
      stars: 115000,
      quality_score: 90,
      tier: 'A',
      scan_date: '2026-06-22T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 12,
      total_files: 20000,
      forks: 17000,
      description: 'Go language',
      topics: ['go', 'language', 'concurrency'],
    },
    {
      id: 'repo-5',
      name: 'rust-lang/rust',
      repo_name: 'rust-lang/rust',
      language: 'Rust',
      stars: 95000,
      quality_score: 95,
      tier: 'A',
      scan_date: '2026-06-21T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 8,
      total_files: 18000,
      forks: 13000,
      description: 'Rust language',
      topics: ['rust', 'language', 'systems'],
    },
    {
      id: 'repo-6',
      name: 'axios/axios',
      repo_name: 'axios/axios',
      language: 'JavaScript',
      stars: 103000,
      quality_score: 82,
      tier: 'A',
      scan_date: '2026-06-20T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 3,
      total_files: 2000,
      forks: 9500,
      description: 'HTTP client',
      topics: ['http', 'ajax', 'javascript'],
    },
    {
      id: 'repo-7',
      name: 'nodejs/node',
      repo_name: 'nodejs/node',
      language: 'JavaScript',
      stars: 98000,
      quality_score: 84,
      tier: 'A',
      scan_date: '2026-06-19T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 1,
      total_files: 5000,
      forks: 26000,
      description: 'Node.js runtime',
      topics: ['nodejs', 'javascript', 'runtime'],
    },
    {
      id: 'repo-8',
      name: 'expressjs/express',
      repo_name: 'expressjs/express',
      language: 'JavaScript',
      stars: 64000,
      quality_score: 78,
      tier: 'B',
      scan_date: '2026-06-18T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 2,
      total_files: 1500,
      forks: 14000,
      description: 'Web framework',
      topics: ['express', 'nodejs', 'web'],
    },
    {
      id: 'repo-9',
      name: 'kubernetes/kubernetes',
      repo_name: 'kubernetes/kubernetes',
      language: 'Go',
      stars: 110000,
      quality_score: 87,
      tier: 'A',
      scan_date: '2026-06-17T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 95,
      total_files: 80000,
      forks: 38000,
      description: 'Container orchestration',
      topics: ['kubernetes', 'containers', 'devops'],
    },
    {
      id: 'repo-10',
      name: 'lodash/lodash',
      repo_name: 'lodash/lodash',
      language: 'JavaScript',
      stars: 60000,
      quality_score: 91,
      tier: 'A',
      scan_date: '2026-06-16T10:00:00Z',
      scan_method: 'automated',
      total_dependencies: 0,
      total_files: 4000,
      forks: 8200,
      description: 'Utility library',
      topics: ['lodash', 'javascript', 'utility'],
    },
  ],
  quality_stats: { average: 78.5, median: 82, std_dev: 8.5, min: 45, max: 99 },
  data_source: 'embedded_mock_data',
  data_files_count: 3,
  last_updated: '2026-06-26T12:00:00Z',
};

// Create jest mock functions so tests can use .mockResolvedValueOnce()
export const loadRealScannerData = jest.fn().mockResolvedValue(mockScannerData);
export const getAllRepositories = jest.fn().mockResolvedValue({
  repositories: mockScannerData.recent_scans,
  total: mockScannerData.recent_scans.length,
  page: 1,
  limit: 10,
  pages: 1,
});
export const checkApiHealth = jest.fn().mockResolvedValue({
  status: 'healthy',
  timestamp: new Date().toISOString(),
  data_files_found: 3,
  total_records: 500,
  data_source: 'embedded_mock_data',
});
export const getApiConfig = jest.fn().mockReturnValue({
  baseUrl: 'http://localhost:8000',
  embeddedUrl: '/embedded-data.json',
  endpoints: {
    stats: '/api/stats',
    repositories: '/api/repositories',
    embedded: '/embedded-data.json',
  },
});
export const getEcosystemData = jest.fn().mockResolvedValue({
  ecosystem_comparison: {},
  total_ecosystems: 0,
});
export const getLanguageData = jest.fn().mockResolvedValue({
  languages: mockScannerData.language_distribution,
  top_languages: mockScannerData.top_languages,
});
export const getPatternData = jest.fn().mockResolvedValue({
  dependency_analysis: {},
  file_analysis: {},
  quality_analysis: {},
});
export const refreshDataCache = jest.fn().mockResolvedValue(mockScannerData);
export const isApiAvailable = jest.fn().mockResolvedValue(true);

// Export mock data for direct access in tests
export { mockScannerData };

export default {
  loadRealScannerData,
  getAllRepositories,
  checkApiHealth,
  getApiConfig,
  getEcosystemData,
  getLanguageData,
  getPatternData,
  refreshDataCache,
  isApiAvailable,
  mockScannerData,
};
